### PR TITLE
BoardAra (tictactoe, connect four, othello, clobber, breakthrough)

### PR DESCRIPTION
**Pull request by chooga**
Thank you for contributing to the CrazyAra repository.

Please shortly describe what you changed in the code.
implemented and tested different board game environments (tictactoe, connect four, othello, clobber, breakthrough)

Before submitting this PR, please make sure:
- [x] You have read the _first steps_ section in the [programmer's guide](https://github.com/QueensGambit/CrazyAra/wiki/Programmer's-guide)
- [x] You are using approved terminology
- [x] You have pulled the latest updates from the main repository.

### CODE REVIEW

**Comment by chooga** [comment]
changes done before merging, maybe following changes need to be reverted in order to start BoardAra again.
- engine/src/uci/optionsuci.cpp:	L.:204 Max and MeanInitPly were set to 0,0,99999 in BoardAra
- engine/src/rl/rl_training.py:		L.:112 local import statement reverted; net.eval() wasn't used in BoardAra
- engine/src/rl/Dockerfile:		L.:28 a different image was used (FROM nvcr.io/nvidia/mxnet:20.10-py3)
- DeepCrazyhouse/config/rl_config.py:	L.:19 binary_name reverted
					L.:30 uci_variant can be set to tictactoe, cfour, clobber, flipersi, or breakthrough for BoardAra

**Comment by QueensGambit** [comment]
Hi @chooga , thanks for the PR.
It looks like the tests are failing due to `read_string_from_file()`.

**Comment by QueensGambit** [comment]
We should probably also add some tests for `MODE_BOARDGAME` to ensure you can still build it and it won't break.

**Comment by QueensGambit** [comment]
Added unit tests in https://github.com/QueensGambit/CrazyAra/pull/187/commits/17f25c275b5bc3f77c392d1750057ee8d02761f6.

**Pull request merged**
