### PR TITLE
Rl loop refactoring

### PR DESCRIPTION
**Pull request by maxalexger**
Main Changes:
- Refactored the `rl_loop.py` class into 5 classes. 
- `rl_loop.py` contains the main functionality. 
- `binaryio.py` contains the process object to the binary and handles all input and output regarding the binary. 
- `fileio.py` handles all file input and outputs. 
- `rl_utils.py` contains small functions that facilitate reinforcement learning.
- Also: Created new file `rl_config.py` that holds all parameters for reinforcement learning

Small refactoring:
- Added UCI command `getoptions` in C++
- Added function `get_uci_options()` in Python
- Added logging statement, after initializing to see how UCI options internally look like
- Added logging of `TrainConfig` object
- Added `is_atomic` if statement to `chess_related/boardstate.cpp`
- Deleted `nb_games_to_update` in `RLLoop` class
- Added `binary_name` var to `rl_config.py` instead of handling binary mappings in `rl_loop.py`
- Added variable `nb_nn_updates` in `rl_config.py` that controls the number of times new data will be created and the network will be trained
- Changed the variable `nb_epochs` to `nb_training_epochs` in `train_config.py` to better describe that it controls the number of epochs the network is trained after enough new data has been created
- Added a variable `train_type` with possible values in `[SL, RL]` when building `TrainerAgent` and `TrainerAgentMxnet`. This is used as a condition when creating and updating the `RTPT` object inside the trainer. This is necessary, because we don't want the RTPT object and updates for `RL`, because we are using a separate `RTPT` object, which is created outside of the training loop.
- Deleted `cwd` variable in `TrainConfig` as it is not used anywhere.
- Deleted `create_new_contender` method from `rl_loop.py` (not used).
- Defined config variables `rm_nb_files` and `rm_fraction_for_selection` that are used in  `include_data_from_replay_memory_into_training` in config file (so they don't need to be set in `rl_loop.py`).
- Moved all `UCI` options from `rl_loopl.py` to `rl_config.py`
- Defined a new function `set_uci_options` in `binaryio.py` that iterates over the UCi dataclass object to set the uci options in the binary

New Functionalities:

- Each process name includes initials and remaining time in accordance to `RTPT` package
- The binary includes initials and remaining time, the training process renames binary
- New variable `nb_nn_updates` in `rl_config` specifies how many epochs we want to train. 1 epoch is defined as waiting for new data and executing 1 training run
- The binary now has the uci option `getoptions` which return all the uci options as they are currently set within the binary
- New python function `get_uci_options` that gets the uci options from binary via `getoptions` and parses them into a dictionary. This is now logged when training is started.

### CODE REVIEW

**Comment by QueensGambit** [comment]
Hi @maxalexger ,
as briefly discussed today, I very much welcome these changes.

I'm only wondering if we should make a more clear distinction between `getoptions` and the `uci` command.
Some alternative names which come to my mind are `activeoptions`, `getactiveoptions` or `currentoptions`.
What do you think?

**Comment by maxalexger** [comment]
Hello @QueensGambit, thank you for the fast answer. I agree that the name of the new UCI option is not well chosen and really like your suggestion of `activeuci`. I will change it in the next days and recommit. Please let me know if you have any other suggestions.

**Comment by QueensGambit** [comment]
I have another small suggestion before merging.
How about changing the new parameter `train_type : str` into `use_rtpt : bool`.
Then `use_rtpt : bool = False` can be added to [train_config_template](https://github.com/QueensGambit/CrazyAra/blob/master/DeepCrazyhouse/configs/train_config_template.py#L104) to be the default value for reinforcement learning.
In the header of the **train_cnn.ipynb** file, `use_rtpt` will be set to `True`.
The only downside I see for this change, is that it might be confusing that rtpt will be active in RL anyway but managed from the `rl_loop.py` anyway.
A small comment in [train_config_template](https://github.com/QueensGambit/CrazyAra/blob/master/DeepCrazyhouse/configs/train_config_template.py#L104) could clarify this.

**Comment by QueensGambit** [comment]
Looks good to me, thanks for the updates.

**Pull request merged**
